### ISSUE TITLE
Attempt to index a nil value

### ISSUE THREAD

**Issue by bloodycop7** [wrefgtzweve/luapad#7]
Error
![image](https://github.com/user-attachments/assets/331328b7-e002-4f44-95f7-361cd9f14219)
![image](https://github.com/user-attachments/assets/66c60dd7-84df-4a03-ba76-12878fdd7ff8)

Happens when you press Close all or Close all but this on a single remaining file.

**Comment by wrefgtzweve** [comment]
Fixed in https://github.com/wrefgtzweve/luapad/commit/1b85ba2329fd46960d1820d856eda4c85b9d2cd9
